ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanOrderId" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanStatus" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanTrackingNumber" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanCourierName" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanTrackingUrl" TEXT;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanStatusRaw" JSONB;
ALTER TABLE "Order" ADD COLUMN IF NOT EXISTS "azanStatusSyncedAt" TIMESTAMP(3);
