export interface District {
  slug: string;
  name: string;
}

export const districts: District[] = [
  { slug: 'dhaka', name: 'Dhaka' },
  { slug: 'faridpur', name: 'Faridpur' },
  { slug: 'gazipur', name: 'Gazipur' },
  { slug: 'gopalganj', name: 'Gopalganj' },
  { slug: 'jamalpur', name: 'Jamalpur' },
  { slug: 'kishoreganj', name: 'Kishoreganj' },
  { slug: 'madaripur', name: 'Madaripur' },
  { slug: 'manikganj', name: 'Manikganj' },
  { slug: 'munshiganj', name: 'Munshiganj' },
  { slug: 'mymensingh', name: 'Mymensingh' },
  { slug: 'narayanganj', name: 'Narayanganj' },
  { slug: 'narsingdi', name: 'Narsingdi' },
  { slug: 'netrokona', name: 'Netrokona' },
  { slug: 'rajbari', name: 'Rajbari' },
  { slug: 'shariatpur', name: 'Shariatpur' },
  { slug: 'sherpur', name: 'Sherpur' },
  { slug: 'tangail', name: 'Tangail' },
  { slug: 'bogura', name: 'Bogura' },
  { slug: 'joypurhat', name: 'Joypurhat' },
  { slug: 'naogaon', name: 'Naogaon' },
  { slug: 'natore', name: 'Natore' },
  { slug: 'nawabganj', name: 'Nawabganj' },
  { slug: 'pabna', name: 'Pabna' },
  { slug: 'rajshahi', name: 'Rajshahi' },
  { slug: 'sirajgonj', name: 'Sirajgonj' },
  { slug: 'dinajpur', name: 'Dinajpur' },
  { slug: 'gaibandha', name: 'Gaibandha' },
  { slug: 'kurigram', name: 'Kurigram' },
  { slug: 'lalmonirhat', name: 'Lalmonirhat' },
  { slug: 'nilphamari', name: 'Nilphamari' },
  { slug: 'panchagarh', name: 'Panchagarh' },
  { slug: 'rangpur', name: 'Rangpur' },
  { slug: 'thakurgaon', name: 'Thakurgaon' },
  { slug: 'barguna', name: 'Barguna' },
  { slug: 'barishal', name: 'Barishal' },
  { slug: 'bhola', name: 'Bhola' },
  { slug: 'jhalokati', name: 'Jhalokati' },
  { slug: 'patuakhali', name: 'Patuakhali' },
  { slug: 'pirojpur', name: 'Pirojpur' },
  { slug: 'bandarban', name: 'Bandarban' },
  { slug: 'brahmanbaria', name: 'Brahmanbaria' },
  { slug: 'chandpur', name: 'Chandpur' },
  { slug: 'chattogram', name: 'Chattogram' },
  { slug: 'comilla', name: 'Comilla' },
  { slug: 'coxs-bazar', name: "Cox's Bazar" },
  { slug: 'feni', name: 'Feni' },
  { slug: 'khagrachari', name: 'Khagrachari' },
  { slug: 'lakshmipur', name: 'Lakshmipur' },
  { slug: 'noakhali', name: 'Noakhali' },
  { slug: 'rangamati', name: 'Rangamati' },
  { slug: 'habiganj', name: 'Habiganj' },
  { slug: 'maulvibazar', name: 'Maulvibazar' },
  { slug: 'sunamganj', name: 'Sunamganj' },
  { slug: 'sylhet', name: 'Sylhet' },
  { slug: 'bagerhat', name: 'Bagerhat' },
  { slug: 'chuadanga', name: 'Chuadanga' },
  { slug: 'jashore', name: 'Jashore' },
  { slug: 'jhenaidah', name: 'Jhenaidah' },
  { slug: 'khulna', name: 'Khulna' },
  { slug: 'kushtia', name: 'Kushtia' },
  { slug: 'magura', name: 'Magura' },
  { slug: 'meherpur', name: 'Meherpur' },
  { slug: 'narail', name: 'Narail' },
  { slug: 'satkhira', name: 'Satkhira' },
];

export function getDistrictBySlug(slug: string): District | undefined {
  return districts.find(d => d.slug === slug);
}
